import Head from 'next/head'
import Sidebar from '../components/Sidebar'
import ListCars from '../components/ListCars'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Gestion Voiture</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ListCars />
    </div>
  )
}


